### ISSUE TITLE
Uploading io.BytesIO elements failing

### ISSUE THREAD

**Issue by ttyridal** [havardgulldahl/jottalib#100]
JFSFolder.up throws an AttributeError when using io.BytesIO objects because they have don't have a name attribute.

**Comment by havardgulldahl** [comment]
Thank you for this. So, what's your use case here? Do you have any code using this?

**Comment by ttyridal** [comment]
Basically all kind of in-memory files. On the fly encryption f.ex.

I did some code trying to implement it, but ran out of time :(

**Comment by havardgulldahl** [comment]
Fixed in git head. Now tests like this pass: https://github.com/havardgulldahl/jottalib/blob/master/tests/test_JFS.py#L125
