### ISSUE TITLE
File attributes

### ISSUE THREAD

**Issue by antonhagg** [havardgulldahl/jottalib#107]
Does anyone know what the file state mean?
Especially I wonder what the "added" and "processing" mean. The others are are more self explained. =)
```
 # constants for known file states
    STATE_COMPLETED = 'COMPLETED' # -> JFSFile
    STATE_ADDED = 'ADDED'
    STATE_INCOMPLETE = 'INCOMPLETE' # -> JFSIncompleteFile
    STATE_PROCESSING = 'PROCESSING'
    STATE_CORRUPT = 'CORRUPT'
```

**Comment by havardgulldahl** [comment]
Hello. 

I have never seen the in the wild, so I can't tell.

**Comment by havardgulldahl** [comment]
I'm going to close this now, but @antonhagg , maybe we should add some info in the wiki about this? Maybe a *Jottacloud protocol explained* section? Care to give it a try?
