### ISSUE TITLE
duplicity TLS warning

### ISSUE THREAD

**Issue by georg90** [havardgulldahl/jottalib#109]
I finally made it to setup the duplicity+jottalib backend. duplicity somehow ignored the custom backend file but it's working now.

Btw. I compiled the 0.7.06 version (manually), downloaded https://raw.githubusercontent.com/havardgulldahl/jottalib/master/src/duplicity-backend.py into ````duplicity/backends```` renamed it to ````jottabackend.py```` and installed duplicity using ````sudo python setup.py install```` Now I use a duply profile with a pre and post script to set the Environment (````export JOTTACLOUD_USERNAME="username" + JOTTACLOUD_PASSWORD="password"````)
You then have to use ````sudo -E duply ...```` to keep the environment variables.

EDIT: Just noticed the variables where saved, so that's why it was working.. Now this doesn't work, will update!!

When I use the backup, I get the following HTTPS errors:
````
--- Start running command BKP at 10:19:20.952 ---
Warning: Option --exclude-globbing-filelist is pending deprecation and will be removed in a future release.
--include-filelist and --exclude-filelist now accept globbing characters and should be used instead.
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Lese ausdruckbasierte Dateiliste /home/user/.duply/test/exclude
syncing https://www.jottacloud.com/jfs/username/Jotta/Sync/test
Synchronisiere entfernte Metadaten zum lokalen Cache...
Lokal /home/user/.cache/duplicity/duply_test/duplicity-full-signatures.20160321T103149Z.sigtar.gz wird gelöscht (keine Auswirkungen am Hintergrundprogramm).
Lokal /home/user/.cache/duplicity/duply_test/duplicity-full.20160321T103149Z.manifest wird gelöscht (keine Auswirkungen am Hintergrundprogramm).
Letzte vollständige Sicherung: keine
Keine Signaturen gefunden, führe vollständiges Backup durch.
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
````

Can somebody explain if this is a serious issue?

**Comment by jkaberg** [comment]
@georg90 http://stackoverflow.com/questions/29134512/insecureplatformwarning-a-true-sslcontext-object-is-not-available-this-prevent

**Comment by georg90** [comment]
@jkaberg thanks for quick help. I somehow thought this must have been an issue with jotta, since it didn't gave me this on other backup profiles.. my mistake!

I used this to satisfy urllib3: ```pip install pyopenssl ndg-httpsclient pyasn1``` on ubuntu 14.04
