### ISSUE TITLE
Add duplicati integration

### ISSUE THREAD

**Issue by tronder88** [havardgulldahl/jottalib#110]
Just saw the comment regarding GUI, is it not possible to integrate this system with Duplicati? Thinking about Duplicati 2.0 as this runs on all systems.

**Comment by havardgulldahl** [comment]
Hey, what GUI comment are you referring to? 

I haven't used Duplicati myself, but I'm sure it would work. Have you tried it yourself?

**Comment by havardgulldahl** [comment]
i see it's written in C#, so writing a plugin for Duplicati is out of scope for this project.

I guess any production level gui would have to go through duplicity, see #108.

 I'd be interested to help out anyone wanting to port `jottalib`, to any platform, though. Get in touch if that is you, @tronder88 :D
