### ISSUE TITLE
jotta-download broken (on folders)?

### ISSUE THREAD

**Issue by sjurtf** [havardgulldahl/jottalib#119]
There seems to be a problem in the latest version here.

Running 0.5.0 on Python 2.7.
sjurtf@home:~$ pip show jottalib
Metadata-Version: 2.0
Name: jottalib
Version: 0.5.0

Here is a stacktrace using loglevel debug.

> sjurtf@home:~$ jotta-download -l debug /Jotta/Archive/<folder>
> DEBUG:jottalib.JFS:getting url: 'https://www.jottacloud.com/jfs/<account>/Jotta/Archive/<folder>', extra_headers=None, params=None
> send: 'GET /jfs/<account>/Jotta/Archive/<folder> HTTP/1.1\r\nHost: www.jottacloud.com\r\nAccept-Encoding: identity\r\nX-JottaAPIVersion: 2.2\r\nUser-Agent: jottalib 0.5.0 (https://github.com/havardgulldahl/jottalib)\r\nAuthorization: Basic <removed>\r\n\r\n'
> reply: 'HTTP/1.1 200 OK\r\n'
> header: Date: Mon, 01 Aug 2016 18:22:46 GMT
> header: Accept-Ranges: bytes
> header: X-ID: 570367400
> header: Content-Type: text/xml
> header: Transfer-Encoding: chunked
> header: Server: Jetty(8.1.4.v20120524)
> DEBUG:requests.packages.urllib3.connectionpool:"GET /jfs/<account>/Jotta/Archive/<folder> HTTP/1.1" 200 None
> Traceback (most recent call last):
>   File "/usr/local/bin/jotta-download", line 11, in <module>
>     sys.exit(download())
>   File "/usr/local/lib/python2.7/dist-packages/jottalib/cli.py", line 280, in download
>     total_size = remote_file.size
> AttributeError: 'JFSFolder' object has no attribute 'size'
>

**Comment by sjurtf** [comment]
I'll just add that this issue only shows on folders. Downloading files using jotta-download works fine.

**Comment by havardgulldahl** [comment]
Yes, thank you @sjurtf for the report. We have some code in a PR that will fix that. I'll go through the code.
