### ISSUE TITLE
JFS - name change?

### ISSUE THREAD

**Issue by rkarlsba** [havardgulldahl/jottalib#120]
JFS is commonly known as the filesystem from IBM, https://en.wikipedia.org/wiki/JFS_(file_system), so perhaps the jotta filesystem should find a better name than JFS, perhaps something like JoFS?

**Comment by havardgulldahl** [comment]
Hey @rkarlsba 
I agree that when you hear `JFS` by itself is probably not the JottaCloud File System that first comes to mind. 
Nevertheless, that is the abbreviation that the company uses themselves, and we want to stay as close to their code as possible. 
So thanks for the thought, but we're sticking with `JFS`.
