### ISSUE TITLE
jotta-download not downloading 0 byte files 

### ISSUE THREAD

**Issue by sjurtf** [havardgulldahl/jottalib#132]
While working on issue #130 I discovered that jotta-download does not respect files that are 0 bytes.

When I was testing my fix for #130 I used the jottalib source code. I uploaded it with jotta-scanner, and downloading it again with jotta-download. After diffing the folders one file was missing.

The file src/jottalib/contrib/**init**.py (0 bytes) was not downloaded.
Another file named **init**.py inside src/jottalib/ (20 bytes) was downloaded so the name is not the issue.

No messages is recroded in jottacloudclient.log.

**Comment by antonhagg** [comment]
I had some trouble with zero files so I decided to exclude them and put them in a debug file( see code in the end). Before, corrupted file was hardcoded as zero size to indicate a corrupt file. I think there has been modifications to JFS to fix this issue but I'm not sure.

**Comment by sjurtf** [comment]
The current code prints an error message.
'<filename> was NOT downloaded successfully - zero file'

The design of download now does not support files with zero size.
When discovered the error message above is printed and the name is added to a list called zero_files. When jotta-download exits the number of zero byte files are printed.

**Comment by sjurtf** [comment]
Ok @antonhagg, so Jotta is treating corrupted files as 0 bytes in their filesystem?
So we can't know if the file is a real zero byte file or a corrupted file?

**Comment by antonhagg** [comment]
Sorry, not corrupted. Incomplete... look in the initial in JFS....

**Comment by antonhagg** [comment]
--init--

**Comment by havardgulldahl** [comment]
@sjurtf @antonhagg this is an obvious bug.  
There are no problems in detecting corrupt or incomplete files, they are instances of `JFSIncompleteFile` and `JFSCorrupFile`.
