### ISSUE TITLE
Suggestion: fork

### ISSUE THREAD

**Issue by Fjodor42** [havardgulldahl/jottalib#148]
Hi @havardgulldahl,

Having recently opened an account with Jotta, I have been looking into some changes and fixes, as you might have noticed.

I shall be more than happy to continue contributing to this repo, but if, as some have suggested, your interest in this project has waned, I would like to know if you would mind if I continue development in my own repo, also adding my own name (with proper attribution to all of your great work, of course)?

Best regards,

F

**Comment by sirasjad** [comment]
@Fjodor42 Bring the project back to life, please! I hate using Jottacloud with Wine, I'm desperate!

**Comment by Fjodor42** [comment]
@sirajuddin97 Noted, and thank you for your show of confidence, but please see my longer reply at #149.

**Comment by Fjodor42** [comment]
https://github.com/Fjodor42/jottalib-ng/
