### ISSUE TITLE
[Errno 30] Read-only file system

### ISSUE THREAD

**Issue by sickel** [havardgulldahl/jottalib#19]
morten@sorbus:/etc$ python --version
Python 2.7.9
morten@sorbus:/etc$ lsb_release -d
Description:    Debian GNU/Linux 8.0 (jessie)

Having installed the nessesary modules, jottafuse starts with an error message, but seems to manage fine afterwards:

￼￼morten@sorbus:~/Downloads/jottalib-0.2/src$ ./jottafuse.py $HOME/jottafs
DEBUG:root:getting url: https://www.jotta.no/jfs/MortenSickel
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): www.jotta.no
DEBUG:urllib3.connectionpool:"GET /jfs/MortenSickel HTTP/1.1" 200 None
fusermount: failed to open /etc/fuse.conf: Permission denied
DEBUG:fuse.log-mixin:-> init / ()
DEBUG:fuse.log-mixin:<- init None
DEBUG:fuse.log-mixin:-> opendir / ()
DEBUG:fuse.log-mixin:<- opendir 0
DEBUG:fuse.log-mixin:-> readdir / (0L,)
DEBUG:fuse.log-mixin:<- readdir <generator object readdir at 0x7f20055124b0>
DEBUG:root:getting url: https://www.jotta.no/jfs/MortenSickel/Jotta/
DEBUG:fuse.log-mixin:-> getattr / (None,)
DEBUG:root:getting url: https://www.jotta.no/jfs/MortenSickel/
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): www.jotta.no
DEBUG:urllib3.connectionpool:"GET /jfs/MortenSickel/ HTTP/1.1" 200 None
DEBUG:fuse.log-mixin:<- getattr {'st_mtime': 1423081334.606577, 'st_mode': 16877, 'st_size': 0, 'st_gid': 1000, 'st_uid': 1000, 'st_atime': 1423081334.606566}

I can then cd into $HOME/jottafs

morten@sorbus:~/Hanne/cowplot$ ls /home/morten/jottafs/Jotta/
Archive  Shared  Sync

but if I try to copy a file, it does not work

morten@sorbus:~/Hanne/cowplot$ ls -l test.png 
-rw-r--r-- 1 morten morten 131477 Dec 29  2013 test.png
morten@sorbus:~/Hanne/cowplot$ cp test.png /home/morten/jottafs/Jotta/
cp: cannot create regular file ‘/home/morten/jottafs/Jotta/Archive/test.png’: Read-only file system
morten@sorbus:~/Hanne/cowplot$ 

and in the log:

DEBUG:fuse.log-mixin:-> getattr /Jotta (None,)
DEBUG:root:getting url: https://www.jotta.no/jfs/MortenSickel/Jotta
DEBUG:root:getting url: https://www.jotta.no/jfs/MortenSickel/Jotta/
DEBUG:fuse.log-mixin:<- getattr {'st_mtime': 1423081671.446705, 'st_mode': 16877, 'st_size': 0, 'st_gid': 1000, 'st_uid': 1000, 'st_atime': 1423081671.446699}
DEBUG:fuse.log-mixin:-> getattr /Jotta/Archive (None,)
DEBUG:root:getting url: https://www.jotta.no/jfs/MortenSickel/Jotta/Archive
DEBUG:fuse.log-mixin:<- getattr {'st_mtime': 1423081671.454177, 'st_mode': 16877, 'st_size': 0, 'st_gid': 1000, 'st_uid': 1000, 'st_atime': 1423081671.454166}
DEBUG:fuse.log-mixin:-> getattr /Jotta/Archive/test.png (None,)
DEBUG:root:getting url: https://www.jotta.no/jfs/MortenSickel/Jotta/Archive/test.png
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): www.jotta.no
DEBUG:urllib3.connectionpool:"GET /jfs/MortenSickel/Jotta/Archive/test.png HTTP/1.1" 404 None
DEBUG:fuse.log-mixin:<- getattr '[Errno 2] '
DEBUG:fuse.log-mixin:-> getattr /Jotta/Archive/test.png (None,)
DEBUG:root:getting url: https://www.jotta.no/jfs/MortenSickel/Jotta/Archive/test.png
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): www.jotta.no
DEBUG:urllib3.connectionpool:"GET /jfs/MortenSickel/Jotta/Archive/test.png HTTP/1.1" 404 None
DEBUG:fuse.log-mixin:<- getattr '[Errno 2] '
DEBUG:fuse.log-mixin:-> create /Jotta/Archive/test.png (33188L,)
DEBUG:fuse.log-mixin:<- create '[Errno 30] Read-only file system'

I also tried to copy into a folder that was created when I synced over a few files from my phone using the android client, $HOME/jottafs/FP1 - but with the same result 

Have I overlooked something? Please tell me if you need some more details from the output or other parts of my configuration.

**Comment by havardgulldahl** [comment]
I'm really sorry to leave you hanging like this.

There has been quite a lot of changes since you reported the issue. I am certain that this particular issue is fixed with the latest code. 

Please reopen this bug if you still trip over this. Thanks!
