### ISSUE TITLE
Lets get this rocking!

### ISSUE THREAD

**Issue by jkaberg** [havardgulldahl/jottalib#20]
Hey Håvard, how about we get this alive and kicking again? (by that I mean large file support etc :smile: )

I dont remember what logs you need of me, could you tell me again?

@havardgulldahl

**Comment by havardgulldahl** [comment]
Yes. This spring has been really busy, and I've neglected this project for
too long.

Let's get back on the road with this circus!

On Sun, May 24, 2015 at 5:54 PM, Joel Kåberg <notifications@github.com>
wrote:

> Hey Håvard, how about we get this alive and kicking again? (by that I mean
> large file support etc [image: :smile:] )
>
> I dont remember what logs you need of me, could you tell me again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/havardgulldahl/jottalib/issues/20>.
>



-- 
Håvard Gulldahl <havard@gulldahl.no>
Telefon: 9971 0615
http://lurtgjort.no/

**Comment by alexschrod** [comment]
Despite having a few minor issues and missing a few features (most glaringly, partial file upload support), this software works quite well. I run a cronjob every night keeping my backup in sync, and I have no real problems at this time. I feel secure that should my file storage system buckle, my most important files are safe and sound. :+1:

**Comment by jkaberg** [comment]
I'm mostly leaning towards issues #11 #12 and #3, before these gets resolved I'm not in an position to use the lib

If @havardgulldahl dosn't pick it up I'll give it a shot after my exams :-)

**Comment by havardgulldahl** [comment]
@alexschrod That's great! Tell us more. Do you use jottacloudclient.py or something else? Anything special there that needs love? 

Daily backups is my main use case as well. And jottacloudclient.py bombs out on big files, but apart from that my backups run hitch-free. 

@jkaberg Yeah, we need to close those critters. And I need your help! Could you please get a log of you manually pausing and then resuming some file uploads? Cheers!

**Comment by havardgulldahl** [comment]
@jkaberg You mentioned #3 . The OP on that thread had caching issues with the FUSE module. Have you had caching issues in other situations?

**Comment by jkaberg** [comment]
@havardgulldahl I can only recall one time where I noticed that behaviour and it's the same as in OP @ #3

**Comment by alexschrod** [comment]
@havardgulldahl Sure, I have this script that runs every night:

    #!/bin/bash

    export JOTTACLOUD_USERNAME="mail@example.com"
    export JOTTACLOUD_PASSWORD="****"

    ENCFS_PASSWORD="****"

    SOURCE_FOLDERS=( /opt/filestore/Documents /opt/filestore/Videos/Personal /opt/filestore/Photos )

    # Create temporary directory to use as encrypted mount-point
    MOUNT_DIR=$(mktemp -d)

    for SOURCE_FOLDER in "${SOURCE_FOLDERS[@]}"
    do
      FOLDER_NAME=$(basename $SOURCE_FOLDER)
      ENCRYPTED_NAME="${FOLDER_NAME}-encrypted"

      # Mount encrypted backup folder
      echo $ENCFS_PASSWORD | encfs -S --reverse $SOURCE_FOLDER $MOUNT_DIR
      
      # Sync with Jotta
      jottacloudclientscanner.py "$MOUNT_DIR/" "/Home/${ENCRYPTED_NAME}/"

      # Unmount encrypted backup folder
      fusermount -u $MOUNT_DIR
    done

    # Delete temporary encrypted mount point
    rm -rf $MOUNT_DIR

    exit 0

Mine has a little extraneous stuff, because I auto-encrypt my stuff before I back it up, using another FUSE filesystem called encfs. This code runs without issue every night, and I've verified multiple times by running it manually that it works well.

I think it hiccups on symbolic links, but I'm not even sure that Jotta supports that, so that's not that big a deal in the long run.

**Comment by alexschrod** [comment]
By the way, I can't remember where I found the 'jottacloudclientscanner.py' file and associated stuff. I just remember it was on a different site than GitHub, for some unexplained reason.

**Comment by havardgulldahl** [comment]
@alexschrod Thanks for sharing your setup. We should probably populate a wiki with use cases and examples. Like, *real* documentation, not just code. ;)

Anyway, I've shut down the separate repository for jottacloudclientscanner and included it in jottalib proper. Seems more natural.

Oh, and please add a new bug report for the symlink issue.

**Comment by alexschrod** [comment]
This project died down again awfully quickly. I was hoping it was going to spring to life for a little longer than a week.

**Comment by havardgulldahl** [comment]
@alexschrod @jkaberg You're the most vocal users. If you want this rocking, I need your help. 

What's your feeling here? How does the current git code run for you? Any big bugs that prevent us from releasing a new version of jottalib?

**Comment by jkaberg** [comment]
Well currently (upload) speeds is the biggest issue for me (maxing out at
10kbps on a 1gbit line). I'd love to see your feature branches finished and
merged, which should solve my issue.
21. jun. 2015 20.36 skrev "Håvard Gulldahl" <notifications@github.com>:

**Comment by havardgulldahl** [comment]
I'm closing this now. Music is everywhere.
