### ISSUE TITLE
Support resume of unfinished upload

### ISSUE THREAD

**Issue by havardgulldahl** [havardgulldahl/jottalib#22]
With #13 fixed, we can recognize unfinished uploads. Now we should be able to resume where we left off last time.

(Note that this is not related to streaming uploads in #11 , as well as arbitrary adding to an existing file. This bug is tracking the ability to pause and continue the upload of the same file)

**Comment by jkaberg** [comment]
Re-posting logs from issue #11
https://gist.github.com/jkaberg/f387a9de553f374a202c
https://gist.github.com/jkaberg/a20b80291eb041801540

**Comment by havardgulldahl** [comment]
Thanks, @jkaberg , could you please get me one more. This time I need the data as well, not just the headers. 

So if you could start syncing some new files in the client, and then pausing, quitting and restarting.

I need to figure out the best way to discover incomplete uploads.

**Comment by jkaberg** [comment]
@havardgulldahl Here's the log, https://jkaberg.com/uploads/misc/1_Full.txt

Since it contains the raw data it's quite big

Let me know how it goes :smiley:

**Comment by havardgulldahl** [comment]
@jkaberg Unfortunately, those logs didn't really demonstrate incomplete files. Did you pause and restart? 

Maybe you could do another round, this time add 4-5 medium-ish files (3-4mb or so), set the client to upload 5 files at the time, and do a few rounds of pausing and restarting... 

This way we'll be able to see exactly how the client is supposed to behave on resumed uploads.

**Comment by jkaberg** [comment]
@havardgulldahl yeah I did, several times actually (just as you described)

You still need the logs?

**Comment by havardgulldahl** [comment]
fixed in jottalib 519292a1f9e942d2ead67b6a995fc55405e0b24e

but we still need to add support to our tools, like `jottacloudclientscanner.py` and friends
