### ISSUE TITLE
Symlinks with non-existent targets cause IOError

### ISSUE THREAD

**Issue by alexschrod** [havardgulldahl/jottalib#28]
As I mentioned in issue #20 I encrypt my files with encfs before I back them up. This causes symlinks to break in the encrypted version of the filesystem.

Jottalib reacts to "invalid" symlinks in the following manner:

    Ouch. Something's wrong with "/tmp/tmp.f7bvJEklz3/JFt1O6BOCP68QNIL430Ggrb2/BHn20qqG1QgosXO36sl6Nhcy/u39r-N7aeQdbsVMxbd0L2BE5/p613RPVEZhp,ys4Dm85Y2OxL":
    ERROR:root:SAFERUN: Got exception when processing (u'/tmp/tmp.f7bvJEklz3/JFt1O6BOCP68QNIL430Ggrb2/BHn20qqG1QgosXO36sl6Nhcy/u39r-N7aeQdbsVMxbd0L2BE5/p613RPVEZhp,ys4Dm85Y2OxL', u'/Home/Documents-encrypted/JFt1O6BOCP68QNIL430Ggrb2/BHn20qqG1QgosXO36sl6Nhcy/u39r-N7aeQdbsVMxbd0L2BE5/p613RPVEZhp,ys4Dm85Y2OxL', <jottalib.JFS.JFS object at 0x1c33b90>, <function callback at 0x1c35c08>)
    Traceback (most recent call last):
      File "/home/alex/dev/jottacloudclient/src/jottacloudclientscanner.py", line 85, in saferun
        return apply(cmd, args)
      File "/home/alex/dev/jottacloudclient/src/jottacloudclient/jottacloud.py", line 94, in new
        with open(localfile) as lf:
    IOError: [Errno 2] No such file or directory: u'/tmp/tmp.f7bvJEklz3/JFt1O6BOCP68QNIL430Ggrb2/BHn20qqG1QgosXO36sl6Nhcy/u39r-N7aeQdbsVMxbd0L2BE5/p613RPVEZhp,ys4Dm85Y2OxL'

I'm not sure Jotta (and therefore jottalib) supports symlinks at all, but if it does, this should not cause an error. A symlink that links to a non-existent file is still a valid symlink.

**Comment by havardgulldahl** [comment]
I don't want to be too clever and do something that the official client doesn't support. Either we ignore symlinks all together, or we back the content up under the symlinked file name.

Both approaches have their downsides. 

What would a majority of users expect?

**Comment by alexschrod** [comment]
I'm not sure just not supporting symlinks gives people the expected behavior. It certainly means that if I took a backup and did a restore, I wouldn't get back what I originally backed up.

**Comment by havardgulldahl** [comment]
@alexschrod Yes. Propose a solution and then we have something to discuss.
