### ISSUE TITLE
Caching issues?

### ISSUE THREAD

**Issue by rkarlsba** [havardgulldahl/jottalib#3]
Hi

Thanks for the work so far. I've run into some issues, perhaps due to caching somewhere (jottalib? fuse? no idea). To reproduce, mount and cd into Archive, run "mkdir somedir, ls -l (it's not there), cd somedir (works), cd .., ls -l (still not there) etc. Ran into some issues with rmdir only (partly?) working as well. See http://karlsbakk.net/tmp/jottatest.txt.gz for a log. Remounting the jotta drive refreshes things and things look sane once again.

roy

**Comment by havardgulldahl** [comment]
We're not caching anything now, so closing
