### ISSUE TITLE
[FUSE] WARNING:root:Unknown jfs object: <type 'lxml.objectify.ObjectifiedElement'> <-> "user"

### ISSUE THREAD

**Issue by jkaberg** [havardgulldahl/jottalib#34]
>WARNING:root:Unknown jfs object: < type 'lxml.objectify.ObjectifiedElement' > <-> "user"

Whenever using **ls** or equivalent on a fuse mount the console outputs warning above

**Comment by havardgulldahl** [comment]
fixed in development branch, thanks
