### ISSUE TITLE
[FUSE] Copying files fails (TypeError: an integer is required)

### ISSUE THREAD

**Issue by jkaberg** [havardgulldahl/jottalib#35]
>Traceback (most recent call last):
>  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 414, in _wrapper
>    return func(*args, **kwargs) or 0
>  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 483, in open
    fi.flags)
>TypeError: an integer is required

When trying to copy a file (using **cp**) from a jotta fuse mount to local it fails with the above error

**Comment by jkaberg** [comment]
Seems to be fixed with latest changes in develop branch

**Comment by havardgulldahl** [comment]
Thanks!
