### ISSUE TITLE
 object of type 'MultipartEncoder' has no len()

### ISSUE THREAD

**Issue by jkaberg** [havardgulldahl/jottalib#36]
>Traceback (most recent call last): 0/10240000 - 00:00:00
>  File "speedtest.py", line 76, in <module>
>    fileobj = jfs.up(p, testfile, upload_callback=UP)
>  File "/usr/local/lib/python2.7/dist-packages/jottalib/JFS.py", line 823, in up
>    return self.post(url, None, files=files, params=params, extra_headers=headers, upload_callback=upload_callback)
>  File "/usr/local/lib/python2.7/dist-packages/jottalib/JFS.py", line 754, in post
    m_len = len(m)
>TypeError: object of type 'MultipartEncoder' has no len()

Happends when I run tests/speedtest.py

**Comment by havardgulldahl** [comment]
I see that the test is picking up the system jottalib, so that is the problem.

You should run this code in a virtualenv so it will run with the git code.

**Comment by havardgulldahl** [comment]
On further inverstigation, I see you're quite right. The api of MultipartEncoder from requests.toolbelt changed slightly in the newest release. Fixed now. Thanks!
