### ISSUE TITLE
AttributeError: 'builtin_function_or_method' object has no attribute 'seek'

### ISSUE THREAD

**Issue by jkaberg** [havardgulldahl/jottalib#38]
>Traceback (most recent call last):
>  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 414, in _wrapper
>    return func(*args, **kwargs) or 0
>  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 515, in write
>    offset, fh)
>  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 881, in __call__
>    ret = getattr(self, op)(path, *args)
>  File "/usr/local/bin/jottafuse.py", line 332, in write
>    buf.seek(offset)
>AttributeError: 'builtin_function_or_method' object has no attribute 'seek'
>Traceback (most recent call last):
>  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 414, in _wrapper
>    return func(*args, **kwargs) or 0
>  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 515, in write
>    offset, fh)
>  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 881, in __call__
>    ret = getattr(self, op)(path, *args)
>  File "/usr/local/bin/jottafuse.py", line 332, in write
>    buf.seek(offset)
>AttributeError: 'builtin_function_or_method' object has no attribute 'seek'
>Traceback (most recent call last):
>  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 414, in _wrapper
>    return func(*args, **kwargs) or 0
>  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 540, in release
>    return self.operations('release', path.decode(self.encoding), fh)
>  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 881, in __call__
>    ret = getattr(self, op)(path, *args)
>  File "/usr/local/bin/jottafuse.py", line 235, in release
>    f.seek(0, os.SEEK_END)
>AttributeError: 'builtin_function_or_method' object has no attribute 'seek'

This seem's to only happen when mounting first jottafuse then on top of that mounting EncFS and then trying top **cp** a file into the unencrypted directory (aka the encrypted directory hosted on jotta)

Is it solvable? Using EncFS on top of jotta for additional security would be a nice thing to have/do

**Comment by havardgulldahl** [comment]
Thanks for your report!
