### ISSUE TITLE
Convert path operations using os.path.join() to "/".join()

### ISSUE THREAD

**Issue by havardgulldahl** [havardgulldahl/jottalib#39]
We need this for windows compability. Every invocation of `os.path.join` should be checked and if need be, changed.

Just like @thusoy did here:
https://github.com/thusoy/jottalib/commit/2a8da24aa1ec73aff5d416803612a9b0ab14e9bd#diff-0d491925f77dc90df49511414dd9f158R140

It should be an easy job, and requires zero knowledge of the plumbing. So a great place to start for someone who wants to contribute.

**Comment by mortenlj** [comment]
Another way to do this, is to use posixpath instead of os.path, which gives you all the path-handling logic, while still giving you forward slashes regardless of platform.

**Comment by havardgulldahl** [comment]
Thanks for the suggestion!

**Comment by havardgulldahl** [comment]
@mortenlj Would you be able to take a stab at this bug?

**Comment by mortenlj** [comment]
I'll take a stab at it. Just so I don't misunderstand anything, this is about handling "Jotta-paths", which are essentially parts of an URL, correct?

**Comment by havardgulldahl** [comment]
Great! Yes, that's right.

søn. 30. aug. 2015 kl. 21.39 skrev Morten Lied Johansen <
notifications@github.com>:
