### ISSUE TITLE
Rename poorly named utilities

### ISSUE THREAD

**Issue by havardgulldahl** [havardgulldahl/jottalib#56]
Following suit from @thusoy's #16 feature fork, we need to rename `jottacloudclientscanner.py` and `jottacloudclientmonitor.py`. For consistency and to reduce the risk of carpal tunnel syndrome.

**Comment by jkaberg** [comment]
As you suggested in gitter, ```jotta-scanner``` and ```jotta-monitor``` seems reasonable to me

**Comment by jkaberg** [comment]
The cli tools, perhaps an entry point like ```jotta``` and then sub point like ```rm``` ```mkdir``` etc would be better then having dedicated entrypoints for all?

Example usage would be 
```jotta mkdir /yada/yada```

```jotta rm /yada/yada/*```

**Comment by thusoy** [comment]
@jkaberg That is a possibility. One of the nice things of having separate commands is easy shell completions. It also prevents the monstrosity that often occurs with nested command parters and other cleverness in the name of DRY when implementing sub-commands. There might be an analogy here to microservices, but I'm not sure. I don't care much either way, just my $.02.

**Comment by alexschrod** [comment]
There's also the "best of both worlds" approach that e.g. Git takes, where you have both single-command entry, like "git commit" and "git push", but also individual commands, like "git-commit" and "git-push".

**Comment by havardgulldahl** [comment]
I'm happy that you all want to rename.

Personally, I like `jotta-*` best.

But here's another thing for all of you. Would you prefer `jotta-*` or `jottacloud-*`?

**Comment by thusoy** [comment]
The way I've come to think of it, "jotta" is the core service, while all the others are interfaces or functions utilizing the service. jottacloud is the web interface, jottalib the library, jotta-ls lists files, jotta-qt a qt interface, etc. Thus jottacloud-ls would be wrong in my ears.

**Comment by havardgulldahl** [comment]
Sounds about right to me.

**Comment by havardgulldahl** [comment]
fixed in https://github.com/havardgulldahl/jottalib/commit/45352a5ea9ae738687b028cccb2ad55f559e4b98
