### ISSUE TITLE
Folders only existing at jotta is not deleted. Same goes for files inside those folders.

### ISSUE THREAD

**Issue by cowai** [havardgulldahl/jottalib#59]
If I sync a folder to jotta, and then deletes it locally will make it stay undeleted at jotta forever. Is this intended?

**Comment by cowai** [comment]
It looks like in jottacloud.compare that it never gets the tree of jotta top path. Only iterates over the local folders.

**Comment by havardgulldahl** [comment]
Well, it's not the way it should be. Not with the `scanner`, anyway. Thanks for the report.

**Comment by cowai** [comment]
a9c3786 fixes this. I have no idea if this is good code. But hey it works.

**Comment by torarnv** [comment]
What happens if a local folder is temporarily unavailable? Delete operations of whats in Jotta should be very very carefully managed so that we don't end up wiping e.g. backup data due to a temporary issue locally

**Comment by cowai** [comment]
@torarnv Yes, a flag should have to be passed for this I agree.

**Comment by havardgulldahl** [comment]
So we should probably stand on the shoulders of giants here. Someone has probably solved this problem before.

@cowai, would you be able to check out what rclone does in this situation?

And then we'll create a wiki page describing how `jottalib` handles this, to be super explicit here.

**Comment by havardgulldahl** [comment]
Move to milestone 0.5

**Comment by cowai** [comment]
@havardgulldahl 
I believe I implemented this in a local fork some months ago. I will if this code is usable.
I also took a glance on how rclone did it, but didn't grasp it immediately.

I cannot really see the big problems with implementing this really. The basics is just check doing a check for each local folder it iterates to if the state is the same both places.

Let me check my code and come back to you

**Comment by cowai** [comment]
@havardgulldahl 
I actually had forgot that this was implemented here: https://github.com/cowai/jottalib/commit/a9c3786bde728ae62ebbadb0a199d011c6955428

Maybe its not the best implementation. But it should work fine.
This is essentially the same code as before but it does folders instead of files. Remember this issue is not about deleting things at the remote. We already do this. This is for the addition of folders.

**Comment by torarnv** [comment]
Deleting anything from the remote when not present locally should be an explicit operation, both for files and folders, triggered by an explicit `prune` action or a config that enables it. What happens if I eg. set up syncing for `/mnt/backup` that I then mount other folders into, and happened to have the mounts fail for some reason so that the root tree is suddenly (and temporarily) empty? I'd wipe the whole remote backup, no?

**Comment by havardgulldahl** [comment]
@cowai  your code from september looks fine, but are you able to rebase to current git, and send a PR?

I agree with you and @torarnv that syncing to jottacloud shouldn't delete folders unless explicitly specified. Because unless my eyes really fail me, your patch **does** prune at remote: https://github.com/cowai/jottalib/commit/a9c3786bde728ae62ebbadb0a199d011c6955428#diff-a28577d6d85894256b6b11df7ea0280bR130

Maybe you could add a `--prune` switch, @cowai?

**Comment by havardgulldahl** [comment]
And for your last comment, @torarnv . Just in case it ever happens to anyone, I wanted to write this explicitly. The backup would be wiped, but you could undelete in from the JottaCloud web interface.

**Comment by cowai** [comment]
@havardgulldahl @torarnv 
Though I agree there should be an option to activate this. The current behaviour now is deleting files but not folders, which I think is worse. A flag activating both, "--delete" or "--prune" would be the best solution. I will rebase the code and try to release something soon.

**Comment by torarnv** [comment]
@cowai Ah, yeah, we should definitely be consistent in how we deal with files and folders. Agree that a global `prune` flag that enabled both, with default to false, is the best option.

@havardgulldahl Glad to hear the files are retained for some time at the Jotta side, just in case. Do you know if they will then hash new uploads agains deleted content to prevent large re-uploads, just restoring the old file?

**Comment by havardgulldahl** [comment]
Guys, there's a difference between files and folders.

If the local folder is gone, it might be because of mounting issues, and then we need to be cautious and adhere to a `--prune` arg.

But if a local file is gone (but we have the folder), what other reason would there be than it being deleted?
Help me out here if there's something I'm missing.

**Comment by torarnv** [comment]
@havardgulldahl That's a good point. How do you treat symlinks? What would a broken symlink trigger?

**Comment by havardgulldahl** [comment]
... So I propose that the `--prune` flag would be for folders only, because the default expectation of a two way sync would be that if you delete a file locally, it would disappear remotely, too.

If you guys agree, I think maybe the flag should be even more explicit, maybe `--prune-missing-folders` or something like that?

**Comment by havardgulldahl** [comment]
@torarnv We're skipping symlinks in `jotta-scanner`.

**Comment by torarnv** [comment]
Ah, I see, as in not even syncing them to Jotta? Then it should be fine. An explicit flag sounds good.

**Comment by havardgulldahl** [comment]
Yes. https://github.com/havardgulldahl/jottalib/blob/master/src/jottalib/scanner.py#L70

**Comment by torarnv** [comment]
(somewhat unrelated, it seems the only way to really have full replicable sync of a HFS+ filesystem is to sync the bands of a sparsebundle, so that you don't need the sync utility, rscyn, jottalib, etc, to support xattrs, symlinks, timestamps, etc. Thoughts?)

**Comment by havardgulldahl** [comment]
Not sure I follow. 
Would you care to explain a bit more?

Skrevet med tommelen




On Fri, Jan 22, 2016 at 8:27 AM -0800, "Tor Arne Vestbø" <notifications@github.com> wrote:












(somewhat unrelated, it seems the only way to really have full replicable sync of a HFS+ filesystem is to sync the bands of a sparsebundle, so that you don't need the sync utility, rscyn, jottalib, etc, to support xattrs, symlinks, timestamps, etc. Thoughts?)

**Comment by cowai** [comment]
@havardgulldahl @torarnv
I think you are right. But the current behaviour is still not a standard way of doing it. Can you think of any sync tool that does delete on files but not folders? 
My suggestion would be to not prune anything as a default, but have the following flags as options:
--prune-files
--prune-folders
--prune-all

Any thoughts?

**Comment by torarnv** [comment]
@havardgulldahl What I mean is if I have I use `jotta-scanner` to sync to Jotta, then delete my local content and restore from Jotta, I wont'a have a 1:1 copy of my original files. I will eg. be missing any symlinks I had in the original file structure. And I'm guessing my file modification timestamps will be wrong, and I'll be missing extended attributes, etc. 

See eg https://www.haystacksoftware.com/blog/category/review/

The only way to ensure a 1:1 sync (copy/backup) is to either have a tool that can sync/retain all the different details of the source filesystem, or to have the sync tool not directly operate on the filesystem files, but on a "simpler" version of the filesystem, such as the individual bands of a sparsebundle image.

https://en.wikipedia.org/wiki/Sparse_image

**Comment by havardgulldahl** [comment]
@torarnv Yes, your observation is 100% correct. In the "standard" mode, where we replicate the way the official clients work, everything else but the file name and contents are effectively discarded. The JottaCloud file system is just as sophisticated as FAT32, it would seem. 

My personal preference is to use a tool like `duplicity`, which will tar up everything for you in a nice container, and store that in the cloud. 

Of course, then you can't get the files one by one, but that's the trade off.

We're going to keep `jotta-scanner` naive and simple. If you're up to adding a more sophisticated tool, we should definitely get something going. Write up a suggestion in a new issue. :+1:

**Comment by cowai** [comment]
@havardgulldahl 
Sending mtime to Jotta would be one thing I think we could do. I think it's better than nothing and I think they actually retain the mtime information. 

I agree that the scanner should be fast and naive.

Btw, before I can fix #59 I need to get jottalib installed. I have written my problem in https://gitter.im/havardgulldahl/jottalib. Could you have a look at the errors and tell me whats wrong?

**Comment by havardgulldahl** [comment]
@torarnv [said](https://github.com/havardgulldahl/jottalib/issues/59#issuecomment-173952324):
> @havardgulldahl Glad to hear the files are retained for some time at the Jotta side, just in case. Do you know if they will then hash new uploads agains deleted content to prevent large re-uploads, just restoring the old file?

I haven't really tested this fully. I don't know what the official client does. 

AFAIK, JottaCloud keeps 5 revisions of every file. There might be some api to restore content just based on md5, but I haven't seen it.

**Comment by havardgulldahl** [comment]
@cowai [said](https://github.com/havardgulldahl/jottalib/issues/59#issuecomment-173972151) 

> My suggestion would be to not prune anything as a default, but have the following flags as options:
> --prune-files
> --prune-folders
> --prune-all

Ok, thanks for your thoughts, @cowai and @torarnv. Here's what I think.

Being a part of a backup suite, I agree that we should err on the side of caution.

So we go with all these flags, and they **default to False**, so nothing gets deleted on the remote side unless it is explicitly specified.

**Comment by torarnv** [comment]
@havardgulldahl :+1:

**Comment by cowai** [comment]
I just pushed https://github.com/cowai/jottalib/commit/5b982278925263f720da643024d4f0d7089b59a9
Its untested for now.
