### ISSUE TITLE
Getting it to work in windows

### ISSUE THREAD

**Issue by antonhagg** [havardgulldahl/jottalib#72]
Dont know if it's my Python knowledge that is a bit limited but I cant get it to work under windows.
Have done both "pip install jottalib" and "pip install jottacloudclient" with no errors but can't get it to load afterwards. is there something more that needs to be done?

/A

**Comment by havardgulldahl** [comment]
Please tell us a bit more about what you are doing, and what the outcome is. As specific as possible. Thanks!

**Comment by antonhagg** [comment]
Ok, so without any previous knowledge of python I did a fresh install of Python 2.7.11.
When doing pip install jottacloudclient and pip install jottalib i ran into some trouble, found out that I needed to install  Microsoft Visual C++ compiler and lxml. I got that installed and ran the pip install jottacloudclient and pip install jottalib again, this time without any errors.

Successfully installed args-0.1.0 certifi-2015.11.20.1 clint-0.5.1 jottacloudclient-0.3.1.post1 jottalib-0.3.1.post1 python-dateutil-2.4.2 requests-2.9.1 requests-toolbelt-0.5.1 six-1.10.0

Now, when looking in the "scrips" folder I have four files that I have no idea how to use (I have tried to read the wiki but cant figure it out):
jottacloudclientmonitor.py
jottacloudclientscanner.py
jottafuse.py
jottashare.py

What i'm trying to do is what it says here, "download a file from my jottaaccount".
https://github.com/havardgulldahl/jottalib/wiki/Normal-use-cases#i-want-to-get-a-file-or-folder-from-backup

Also I don't know where I shall put the .netrc file with my username and password.

Btw anyone know where the default "home" folder is and how I can change it?

**Comment by havardgulldahl** [comment]
Sorry, the release on pypi is lagging severely behind. 

Please install directly from github for now, and tell us how that works for you.

**Comment by havardgulldahl** [comment]
Please try with the latest package from pypi and let us know how it works!

**Comment by antonhagg** [comment]
I tried by getting it directly from github, and it kinda works. 
It gets the wrong root folder (it defaults into the "Sync" folder when running jotta-ls). 
Also there seems to be some errors in the progress.py file, see debug info under.
```
header: Date: Fri, 22 Jan 2016 11:32:19 GMT
header: Accept-Ranges: bytes
header: Content-Type: text/xml
header: Transfer-Encoding: chunked
header: Server: Jetty(8.1.4.v20120524)
DEBUG:requests.packages.urllib3.connectionpool:"GET /jfs/XXX/Jotta/Sync/Jottacloud.pdf HTTP/1.1" 200 None
Traceback (most recent call last):
  File "C:\Python27\Scripts\jotta-download-script.py", line 9, in <module>
    load_entry_point('jottalib==0.4.post1', 'console_scripts', 'jotta-download')()
  File "c:\python27\lib\site-packages\jottalib\cli.py", line 229, in download
    with ProgressBar(expected_size=total_size) as bar:
  File "c:\python27\lib\site-packages\clint\textui\progress.py", line 63, in __init__
    self.show(0)
  File "c:\python27\lib\site-packages\clint\textui\progress.py", line 87, in show
    self.expected_size, self.etadisp))
  File "c:\python27\lib\site-packages\clint\packages\colorama\ansitowin32.py", line 34, in write
    self.__convertor.write(text)
  File "c:\python27\lib\site-packages\clint\packages\colorama\ansitowin32.py", line 115, in write
    self.write_and_convert(text)
  File "c:\python27\lib\site-packages\clint\packages\colorama\ansitowin32.py", line 142, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "c:\python27\lib\site-packages\clint\packages\colorama\ansitowin32.py", line 147, in write_plain_text
    self.wrapped.write(text[start:end])
  File "c:\python27\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 1-32: character maps to <undefined>
```

**Comment by antonhagg** [comment]
Looked in the Cli.py and it actually says that default root should be root. Why is that?

```
Line 68
def get_root_dir(jfs):
    jottadev = get_jotta_device(jfs)
    root_dir = jottadev.mountPoints['Sync']
    return root_dir
```

**Comment by havardgulldahl** [comment]
@antonhagg 
> it actually says that default root should be root

You probably meant .. "the default root shoud be **Sync**", yeah?

There is no particular reason that the Sync folder is the default. It just seemed like a nice idea.

What we're missing is a way to pass the root dir as an argument to the cli scripts. So that is something we need to be able to do. You want to have a go?

**Comment by antonhagg** [comment]
That's correct. Was a bit to quick. =)
Not sure that I understand what your asking for, but is it that all functions in cli.py should have an argument that the "real" root should be used? 

Regarding the other error above (the Unicode error). I'll just open a new issue with that, so I guess this issue can be closed.
