### ISSUE TITLE
jottalib 0.3.1.post1 does not provide the extra 'fuse'

### ISSUE THREAD

**Issue by oyvindlh** [havardgulldahl/jottalib#75]
On OSX 10.11.2, have tried both Python2.7 and Python3.

When I pip install jottalib[FUSE] I get:

Collecting jottalib[fuse]
  Using cached jottalib-0.3.1-1.tar.gz
  jottalib 0.3.1.post1 does not provide the extra 'fuse'

And when trying to run jotta-fuse I get:

ython3 jotta-fuse
/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/Resources/Python.app/Contents/MacOS/Python: can't open file 'jotta-fuse': [Errno 2] No such file or directory

Am I missing something?

**Comment by havardgulldahl** [comment]
Thank you for your report. 

The pypi package is lagging behind the github version. 

Please, could you try installing with `pip` directly from the github repository, and see if that makes any difference? Thanks!

**Comment by havardgulldahl** [comment]
I pushed a new version to pypi last night. I expect that to solve your issues.

If this still does not work as you expect, please reopen this issue and describe your disappointment. And the details of the bug, too :)
