### ISSUE TITLE
xattr not supported under windows

### ISSUE THREAD

**Issue by antonhagg** [havardgulldahl/jottalib#76]
Hi,

It seems that xattr is not supported under windows, is there a way to bypass this in jottacloud.py?
Also, isn't there a risk that if you store the md5 as a file attribute that it will miss uploading it since the md5 file attribute is not updated automatically when the file is changed?

/Anton

**Comment by havardgulldahl** [comment]
This is a bug in `jottacloud.py`.

**Comment by antonhagg** [comment]
Nice, thanks!
