### ISSUE TITLE
Codify canary

### ISSUE THREAD

**Issue by havardgulldahl** [havardgulldahl/jottalib#77]
JottaCloud started publishing a canary warning in 2015, over at https://www.jottacloud.com/canary/

If anyone wants to implement a top-level function to get the canary status, I'd welcome it. It would be a nice way to get acquainted with `jottalib`.

**Comment by cowai** [comment]
@havardgulldahl 
Since the canary will be updated once a week, can we simply extract the date out with regex and if the date is older than a week the canary is dead? We should check the signature as well maybe.

Any thoughts?

**Comment by havardgulldahl** [comment]
Yes, sounds like a sound plan.

**Comment by havardgulldahl** [comment]
@cowai, I don't think we actually need the canary. I don't have any pressing need for it myself. Unless someone comes along and make a compelling case for it, I think we shouldn't bother. After all, **less code=less bugs!**

**Comment by cowai** [comment]
Yes, I agree.
