### ISSUE TITLE
jotta-scanner - UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode

### ISSUE THREAD

**Issue by malinkb** [havardgulldahl/jottalib#79]
I get this error when using jotta-scanner to upload a folder to jottacloud:

`<WARNING:py.warnings:/usr/local/lib/python2.7/dist-packages/jottalib-0.4_1-py2.7.egg/jottalib/JFS.py:92: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal>`

Actual terminal output with -l debug switch
http://paste.debian.net/367149/

snippet from ./jottacloudclient.log

http://paste.debian.net/367150/

**Comment by havardgulldahl** [comment]
Thanks, @malinkb! 

I'll take a look

**Comment by havardgulldahl** [comment]
There's a silly utf8 decoding bug in there. Sorry about that.

**Comment by malinkb** [comment]
Ah. How can it be resolved? Thank you for taking a look :)

**Comment by cowai** [comment]
I have the same problem.

**Comment by cowai** [comment]
@havardgulldahl 
These changes seems to fix the issue, no idea if that is the cause of the real problem though.
```python
-    for data in iter(lambda: fileobject.read(size), u''):
-        md5.update(data.encode('utf-8'))

+    for data in iter(lambda: fileobject.read(size), ''):
+        md5.update(data)

**Comment by havardgulldahl** [comment]
@malinkb Check out the 0.4.1 release and reopen this bug if you still have problems.

**Comment by malinkb** [comment]
Thanks. It actually works now. First I believed otherwise, but it was because I mistyped the name of the destination folder.
