### ISSUE TITLE
Uploads/sync very slow

### ISSUE THREAD

**Issue by rkarlsba** [havardgulldahl/jottalib#8]
Hi

Seems the upload speed with jottalib is a wee bit slower than I hoped it would be. Perhaps 600 kB transferred in an hour. CPU load is low and bandwidth is good (75Mbps, this time from a linux box on cable). Something slightly wrong here? ;)

roy

**Comment by havardgulldahl** [comment]
@rkarlsba, quite a lot has happened here since your initial testing. 

Would you care to give it another try with the latest code in the `development` branch?

**Comment by havardgulldahl** [comment]
I'm closing this, reporter has gone away. Anyway, I think we've come a long way solving this, let me quote @jkaberg from https://gitter.im/havardgulldahl/jottalib:

  >   just wanted to let you guts know the fuse option outperforms the jottacloudclientscanner thing on upload
  >   **getting 10-12MB/s with rsync on it**

**Comment by rkarlsba** [comment]
I gave up on jotta - sorry about it

**Comment by havardgulldahl** [comment]
Ok, bye.
