### ISSUE TITLE
Share doesn't return a url

### ISSUE THREAD

**Issue by jnylen** [havardgulldahl/jottalib#94]
Hi Havard,
When using jotta-share from pip it doesn't return a shareable url when I do this:

> jotta-share OOHAHH.mp3

Would it be possible to get a logging variable for this to indicate what the problem is?

**Comment by havardgulldahl** [comment]
@jnylen Seems like a bug, I have to take a look. Does the command not return  anything at all?

**Comment by havardgulldahl** [comment]
@jnylen Seems like Jottacloud changed their API for sharing files. Trying to figure out the new API.
