### ISSUE TITLE
Pinned version of python2-certifi 

### ISSUE THREAD

**Issue by IceHamster** [havardgulldahl/jottalib#96]
Why is certifi pinned to version 2015.4.28?

Installed the latest python2-certifi, and edited setup.py and i could upload a file to Jottacloud

```
'install_requires=['requests',

-  'certifi==2015.4.28', # TODO: remove pin
+  'certifi', # TODO: remove pin 
```

**Comment by havardgulldahl** [comment]
For historic reasons. While there is no question that we should pin if not needed, are you getting any issues with the old certifi? Just so I understand what you are reporting :)

**Comment by IceHamster** [comment]
I'm asking if the use of an old version of "certifi" is needed?
The latest release is "2015.11.20.1", while the package used in setup.py for jottalib is version "2015.4.28" 
I have installed jottalib with the latest "certifi" release, and it seems to be working. :)

Could we change line 49 in setup.py 
From:
`'certifi==2015.4.28', # TODO: remove pin`
To:
`'certifi'`
