### ISSUE TITLE
Allow jotta-upload to upload directories

### ISSUE THREAD

**Issue by jnylen** [havardgulldahl/jottalib#97]
Hi,
Is it possible to make it so jotta-upload can upload items inside of a directory?

**Comment by antonhagg** [comment]
I did write some code for folder download. It might be similar to folder upload.
It hasen't been included in the master but you can have a look at my code if you want some inspiration. =)

**Comment by havardgulldahl** [comment]
Hey @jnylen, how about I take a look at your PR, and after that is in you can write some code for `jotta-upload`? :D
